### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by imTCA**
It's in the title. This basically adds a license to the repo.

To those interested, the license is the GNU General Public License v3.0.

### CODE REVIEW

**Comment by Ye11owed** [comment]
Now we have the rights to copyright strike every video that talks about this repo. Just kidding.

**Comment by imTCA** [comment]
Very funny. Is this ready to merge?

**Comment by Ye11owed** [comment]
Looks like it.

**Comment by imTCA** [comment]
Got it. Merging...

**Pull request merged**
